export const SCOPES = {
    "tag.attribute": "ATT1",
    "tag.attribute.assignment": "ATT",
    "entity.other.attribute-name.js.xjs": "A_NAME",
    "entity.other.attribute.param.shortcut.js.xjs": "ATT_EXPR",
    "entity.other.attribute.param.spread.js.xjs": "ATT_SPREAD",

    "keyword.operator.optional.ts": "PARAM_OPTIONAL",
    "keyword.operator.assignment.ts": "ASSIGNMENT",

    "meta.arrow.ts": "ARROW_FUNCTION",
    "meta.delimiter.decimal.period.ts": "DECIMAL_PERIOD",
    "meta.type.tuple.ts": "TUPLE",
    "meta.brace.square.ts": "BRACE_SQ",
    "storage.type.function.arrow.ts": "ARROW",

    "meta.block.ts": "BLOCK",
    "meta.block.attributes.ts": "BLOCK_ATT",
    "punctuation.definition.block.ts": "B_DEF",
    "punctuation.section.embedded.begin.js.xjs": "B_START",
    "punctuation.section.embedded.end.js.xjs": "B_END",
    "punctuation.section.embedded.text.expr.xjs": "T_EXP",
    "meta.brace.round.ts": "BRACE_R",

    "punctuation.separator.comma.ts": "COMMA",
    "comment.block.ts": "COMMENT",
    "comment.line.double-slash.ts": "COMMENT1",
    "punctuation.definition.comment.ts": "C_DEF",
    "punctuation.whitespace.comment.leading.ts": "C_WS",
    "content": "CONTENT",

    "entity.other.attribute.decorator.js.xjs": "DECO1",
    "tag.attribute.decorator.assignment": "DECO",
    "punctuation.section.embedded.decorator.js.xjs": "D_DEF",
    "punctuation.section.embedded.decorator.begin.js.xjs": "D_START",
    "punctuation.section.embedded.decorator.end.js.xjs": "D_END",

    "constant.character.escape.ts": "ESC",
    "constant.character.entity.js.xjs": "ENTITY",
    "punctuation.section.embedded.modifier.js.xjs": "EXP_MOD",
    "keyword.operator.assignment.js.xjs": "EQ",

    "meta.function-call.ts": "F_CALL",
    "entity.name.function.ts": "F_NAME",

    "constant.numeric.decimal.ts": "NUM",
    "entity.name.type.module.ts": "MOD",

    "keyword.operator.arithmetic.ts": "OP",

    "variable.other.property.ts": "PROP",
    "meta.parameters.ts": "PARAM",
    "punctuation.definition.parameters.begin.ts": "P_START",
    "punctuation.definition.parameters.end.ts": "P_END",
    "variable.parameter.ts": "P_VAR",
    "tag.attribute.property.assignment": "PR",
    "punctuation.section.embedded.property.begin.js.xjs": "PR_START",
    "punctuation.section.embedded.property.end.js.xjs": "PR_END",
    "entity.other.attribute.property.shortcut.js.xjs": "PR_EXPR",
    "entity.other.attribute.property.spread.js.xjs": "PR_SPREAD",

    "entity.other.attribute.label.js.xjs": "LBL",
    "punctuation.section.embedded.label.js.xjs": "LBL_DEF",
    "entity.other.attribute.ref.js.xjs": "REF",
    "punctuation.section.embedded.ref.js.xjs": "R_DEF",
    "punctuation.section.embedded.ref.collection.js.xjs": "R_COL",
    "punctuation.section.embedded.ref.collection.start.js.xjs": "R_COL_START",
    "punctuation.section.embedded.ref.collection.end.js.xjs": "R_COL_END",

    "source.ts": "S",
    "string.quoted.double.ts": "STR_D",
    "string.quoted.single.ts": "STR_S",
    "punctuation.definition.string.begin.ts": "S_START",
    "punctuation.definition.string.end.ts": "S_END",
    "punctuation.separator.parameter.ts": "SEP",
    "punctuation.terminator.statement.ts": "TERM",

    "xjs.template.ts": "T",
    "meta.tag.js.xjs": "TAG",
    "entity.name.tag.js.xjs": "T_NAME",
    "entity.name.tag.prefix.js.xjs": "T_PREFIX",
    "punctuation.definition.tag.begin.js.xjs": "T_START",
    "punctuation.definition.tag.end.js.xjs": "T_END",
    "punctuation.definition.tag.close.js.xjs": "T_CLOSE",
    "string.xjs.text.node.ts": "TXT",
    "punctuation.definition.string.begin.js.xjs": "TXT_START",
    "punctuation.definition.string.end.js.xjs": "TXT_END",
    "constant.language.boolean.true.ts": "TRUE",

    "meta.type.annotation.ts": "TYPE_AN",
    "entity.name.type.ts": "TYPE_ENTITY",
    "keyword.operator.type.annotation.ts": "TYPE_SEP",
    "support.type.primitive.ts": "TYPE_PRIMITIVE",

    "variable.other.object.ts": "VAR",
    "variable.other.readwrite.ts": "V_RW",
    "punctuation.accessor.ts": "V_ACC",

    "punctuation.section.embedded.block.xjs": "B",
    "if.statement.xjs": "$IF",
    "keyword.control.conditional.xjs": "$if",
    "for.statement.xjs": "$FR",
    "keyword.control.loop.xjs": "$for",
    "meta.var.expr.ts": "VE",
    "meta.var-single-variable.expr.ts": "VSVE",
    "keyword.operator.relational.ts": "OP",
    "meta.definition.variable.ts": "VDF",
    "storage.type.ts": "STT",
    "keyword.operator.increment.ts": "++",
    "exec.statement.xjs": "$E",
    "keyword.control.exec.xjs": "$exec",
    "keyword.control.let.xjs": "$let",
    "each.statement.xjs": "$C",
    "keyword.control.each.xjs": "$each",
    "log.statement.xjs": "$L",
    "keyword.control.log.xjs": "$log",
    "template.statement.xjs": "$T",
    "keyword.control.template.xjs": "$template",
    "meta.definition.function.ts": "FUN",

    "xtc.template.ts": "C",
    "entity.other.attribute.reference.xtc": "REF",
    "punctuation.section.embedded.begin.xjs": "{",
    "punctuation.section.embedded.end.xjs": "}",
    "cdata.content.xjs": "CDC"
}